services:
  - type: web
    name: safe-ph
    env: node
    buildCommand: "pip install -r requirements.txt && npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: PYTHON_PATH
        value: python3
      - key: PYTHON_INSTALL_PATH
        value: ""